/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-15 02:55:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardForm304_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  background-color: #000;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("  background-color: #15172b;\r\n");
      out.write("  border-radius: 20px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  height: 700px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  width: 320px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subtitle {\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-container {\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ic1 {\r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ic2 {\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input {\r\n");
      out.write("  background-color: #303245;\r\n");
      out.write("  border-radius: 12px;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  padding: 4px 20px 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cut {\r\n");
      out.write("  background-color: #15172b;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  left: 20px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: -20px;\r\n");
      out.write("  transform: translateY(0);\r\n");
      out.write("  transition: transform 200ms;\r\n");
      out.write("  width: 76px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cut-short {\r\n");
      out.write("  width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input:focus ~ .cut,\r\n");
      out.write(".input:not(:placeholder-shown) ~ .cut {\r\n");
      out.write("  transform: translateY(8px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".placeholder {\r\n");
      out.write("  color: #65657b;\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("  left: 20px;\r\n");
      out.write("  line-height: 14px;\r\n");
      out.write("  pointer-events: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  transform-origin: 0 50%;\r\n");
      out.write("  transition: transform 200ms, color 200ms;\r\n");
      out.write("  top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input:focus ~ .placeholder,\r\n");
      out.write(".input:not(:placeholder-shown) ~ .placeholder {\r\n");
      out.write("  transform: translateY(-30px) translateX(6px) scale(0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input:not(:placeholder-shown) ~ .placeholder {\r\n");
      out.write("  color: #808097;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input:focus ~ .placeholder {\r\n");
      out.write("  color: #dc2f55;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit {\r\n");
      out.write("  background-color: #08d;\r\n");
      out.write("  border-radius: 12px;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  margin-top: 38px;\r\n");
      out.write("  // outline: 0;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit:active {\r\n");
      out.write("  background-color: #06b;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"post\" action=\"boardWrite304.jsp\">\r\n");
      out.write("<div class=\"form\">\r\n");
      out.write("      <div class=\"title\">게시판 글쓰기</div>\r\n");
      out.write("      <div class=\"subtitle\">글쓰기</div>\r\n");
      out.write("      <div class=\"input-container ic1\">\r\n");
      out.write("        <input id=\"name\" name=\"name\" class=\"input\" type=\"text\" placeholder=\" \" />\r\n");
      out.write("        <div class=\"cut\"></div>\r\n");
      out.write("        <label for=\"name\" class=\"placeholder\">USERID</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-container ic2\">\r\n");
      out.write("        <input id=\"userpwd\" name=\"pass\" class=\"input\" type=\"text\" placeholder=\" \" />\r\n");
      out.write("        <div class=\"cut\"></div>\r\n");
      out.write("        <label for=\"userpwd\" class=\"placeholder\">PASSWORD</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-container ic2\">\r\n");
      out.write("        <input id=\"email\" name=\"email\" class=\"input\" type=\"text\" placeholder=\" \" />\r\n");
      out.write("        <div class=\"cut cut-short\"></div>\r\n");
      out.write("        <label for=\"email\" class=\"placeholder\">Email</>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-container ic2\">\r\n");
      out.write("        <input id=\"title\" name=\"title\" class=\"input\" type=\"text\" placeholder=\" \" />\r\n");
      out.write("        <div class=\"cut cut-short\"></div>\r\n");
      out.write("        <label for=\"title\" class=\"placeholder\">Title</>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-container ic2\">\r\n");
      out.write("        <input id=\"content\" name=\"content\" class=\"input\" type=\"text\" placeholder=\" \" />\r\n");
      out.write("        <div class=\"cut\"></div>\r\n");
      out.write("        <label for=\"content\" class=\"placeholder\">Content</>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <button type=\"submit\" class=\"submit\" value=\"confirm\">등록</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- 	<form method=\"post\" action=\"testLogin261.jsp\"> -->\r\n");
      out.write("	\r\n");
      out.write("<!-- 		<label for=\"userid\"> 아이디 : </label> -->\r\n");
      out.write("<!-- 		<input type=\"text\" name=\"id\" id=\"userid\"><br> -->\r\n");
      out.write("		\r\n");
      out.write("<!-- 		<label for=\"userpwd\"> 암 &nbsp; 호 : </label> -->\r\n");
      out.write("<!-- 		<input type=\"password\" name=\"pwd\" id=\"userpwd\"><br> -->\r\n");
      out.write("		\r\n");
      out.write("<!-- 		<input type=\"submit\" value=\"로그인\"> -->\r\n");
      out.write("	\r\n");
      out.write("<!-- 	</form> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
